# if 는 참과 거짓에 대한 이야기 입니다.
# True, False 는 앞글자가 대문자여야만 합니다.

# A 또는 B가 참 (둘중하나만 참)
# A 그리고 B가 참 (둘다 참)
#
# A=True
# B=False
#
# print(A|B)
# print(A&B)
#
# print(A is True)
# print(A == True)
#
# d=3.3
# if d>5 :
#     print("The number is bigger than 5")
# elif 3<d and d<4:
#     print("The number is smaller or equal with 5")

# range 는 범위
# for num in range(1,10):
#     print(num)
#
# a=1
# while a<10:
#     print(a)
# #     a=a+1
# print("what number of table do you want? ")
# num=input("")
# for num in range
